// ─────────────────────────────────────────────────────────────────────────────
// firebase_options.dart
//
// THIS FILE IS AUTO-GENERATED by FlutterFire CLI.
// Run the following commands to generate the real version:
//
//   1. Install FlutterFire CLI (once):
//        dart pub global activate flutterfire_cli
//
//   2. Log in to Firebase CLI (once):
//        firebase login
//
//   3. In your project root, run:
//        flutterfire configure
//
//      → Select your Firebase project (or create a new one)
//      → Select platforms: Android, iOS (and Web if needed)
//      → This will overwrite THIS FILE with real API keys.
//
// Until you run `flutterfire configure`, the app will throw a Firebase
// initialization error on launch. The placeholder values below are intentional.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run `flutterfire configure` to generate the options.',
        );
    }
  }

  // ── Replace these with values from `flutterfire configure` ────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--r_4eMtzPB2C1B1E2jQcmWHG9X2UbT4',
    appId: '1:671908543018:android:4df813d042bb7ab32a6153',
    messagingSenderId: '671908543018',
    projectId: 'nutrify-52ebf',
    storageBucket: 'nutrify-52ebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSZuqtPMNrmU0khZZbed-fxH-5kqn_9Y4',
    appId: '1:671908543018:ios:90891eee9144eea72a6153',
    messagingSenderId: '671908543018',
    projectId: 'nutrify-52ebf',
    storageBucket: 'nutrify-52ebf.firebasestorage.app',
    iosBundleId: 'com.example.nutrify',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: 'YOUR_WEB_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}